services:
  app:
    image: greutermara/dwm-project:latest
    container_name: dwm_project_container
    ports:
      - "8080:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: dwm_project
      DB_USERNAME: root
      DB_PASSWORD: secret
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:RnI937QlEQnI5eRNlVwZQfGPogCg8zBNeORFl4Z0Ecc=
      SESSION_DRIVER: database
    depends_on:
      - db

  mysql:
    image: mysql:8
    container_name: dwm_mysql
    environment:
      MYSQL_DATABASE: dwm_project
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
